const applicationsList = [
  {
    id: 1,
    name: 'Lizard a ddfde df widespread group',
    memberId: '1',
    row_status: 1,
  },
  {
    id: 2,
    name: 'Lizard a ddfde df widespread group',
    memberId: '1',
    row_status: 0,
    company_name: 'lorem5',
    company_type: 'private',
    email: 'test',
    mobile: 'test',
    designation: 'test',
    company_address: 'test',
  },
  {
    id: 3,
    name: 'Pathao',
    memberId: '2',
    row_status: 1,
    company_name: 'lorem5',
    company_type: 'private',
    email: 'test',
    mobile: 'test',
    designation: 'test',
    company_address: 'test',
  },
  {
    id: 4,
    name: 'Lizard a ddfde df widespread group',
    memberId: '5',
    row_status: 2,
    company_name: 'lorem5',
    company_type: 'private',
    email: 'test',
    mobile: 'test',
    designation: 'test',
    company_address: 'test',
  },
  {
    id: 5,
    name: 'Lizard a ddfde df widespread group',
    memberId: '10',
    row_status: 3,
    company_name: 'lorem5',
    company_type: 'private',
    email: 'test',
    mobile: 'test',
    designation: 'test',
    company_address: 'test',
  },
];

export default applicationsList;
