export interface NavItemProps {
  id: string;
  messageId: string;
  title: string;
  icon?: string;
  exact?: boolean;
  url?: string;
  as?: string;
  type?: string;
  count?: number;
  color?: string;
  auth?: string[];
  permissionKey?: string;
  children?: NavItemProps[] | NavItemProps;
}

const routesConfig: NavItemProps[] = [
  {
    id: 'app',
    title: 'Application',
    messageId: 'menu.application',
    type: 'group',
    children: [],
  },
  {
    id: 'pages',
    title: 'Pages',
    messageId: 'menu.pages',
    type: 'group',
    children: [
      {
        id: 'user_management',
        title: 'User Management',
        messageId: 'menu.user_management',
        type: 'collapse',
        icon: 'people',
        children: [
          {
            id: 'permission_group',
            title: 'Permission Group',
            messageId: 'menu.permission_group',
            permissionKey: 'menu_permission_group',
            type: 'item',
            icon: 'person',
            url: '/dashboard/permission-groups',
          },
          {
            id: 'permission',
            title: 'Permission',
            messageId: 'menu.permission',
            permissionKey: 'menu_permission',
            type: 'item',
            icon: 'person',
            url: '/dashboard/permissions',
          },
          {
            id: 'permission_sub_group',
            title: 'Permission Group',
            messageId: 'menu.permission_sub_group',
            permissionKey: 'menu_permission_sub_group',
            type: 'item',
            icon: 'person',
            url: '/dashboard/permission-sub-groups',
          },
          {
            id: 'roles',
            title: 'Role',
            messageId: 'menu.role',
            permissionKey: 'menu_role',
            type: 'item',
            icon: 'person',
            url: '/dashboard/roles',
          },
          {
            id: 'users',
            title: 'User',
            messageId: 'menu.user',
            permissionKey: 'menu_user',
            type: 'item',
            icon: 'person',
            url: '/dashboard/users',
          },
        ],
      },
      {
        id: 'organization_management',
        title: 'Organization Management',
        messageId: 'menu.organization_management',
        type: 'collapse',
        icon: 'room',
        children: [
          {
            id: 'rank_types',
            title: 'Rank Type',
            messageId: 'menu.rank_type',
            permissionKey: 'menu_rank_type',
            type: 'item',
            icon: 'business',
            url: '/dashboard/rank-types',
          },
          {
            id: 'rank',
            title: 'Rank',
            messageId: 'menu.rank',
            permissionKey: 'menu_rank',
            type: 'item',
            icon: 'business',
            url: '/dashboard/ranks',
          },
          {
            id: 'skill',
            title: 'Skill',
            messageId: 'menu.skill',
            permissionKey: 'menu_skill',
            type: 'item',
            icon: 'business',
            url: '/dashboard/skills',
          },
          {
            id: 'organization_type',
            title: 'Organization Type',
            messageId: 'menu.organization_type',
            permissionKey: 'menu_organization_type',
            type: 'item',
            icon: 'business',
            url: '/dashboard/organization-types',
          },
          {
            id: 'organization',
            title: 'Organizations',
            messageId: 'menu.organization',
            permissionKey: 'menu_organization',
            type: 'item',
            icon: 'businessCenter',
            url: '/dashboard/organizations',
          },
          {
            id: 'organization_unit_type',
            title: 'Organization Unit Type',
            messageId: 'menu.organization_unit_type',
            permissionKey: 'menu_organization_unit_type',
            type: 'item',
            icon: 'businessCenter',
            url: '/dashboard/organization-unit-types',
          },
          {
            id: 'organization_unit',
            title: 'Organization Unit',
            messageId: 'menu.organization_unit',
            permissionKey: 'menu_organization_unit',
            type: 'item',
            icon: 'businessCenter',
            url: '/dashboard/organization-units',
          },
          {
            id: 'job-sectors',
            title: 'Job Sector',
            messageId: 'menu.job_sector',
            permissionKey: 'menu_job_sector',
            type: 'item',
            icon: 'work',
            url: '/dashboard/job-sectors',
          },
          {
            id: 'occupations',
            title: 'Occupations',
            messageId: 'menu.occupations',
            permissionKey: 'menu_occupations',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/occupations',
          },
          {
            id: 'services',
            title: 'services',
            messageId: 'menu.services',
            permissionKey: 'menu_services',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/services',
          },
        ],
      },

      {
        id: 'institute_management',
        title: 'Institute Management',
        messageId: 'menu.institute_management',
        type: 'collapse',
        icon: 'room',
        children: [
          {
            id: 'timeline',
            title: 'Institute',
            messageId: 'menu.institute',
            permissionKey: 'menu_institute',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/institutes',
          },
          {
            id: 'branch',
            title: 'Branch',
            messageId: 'menu.branch',
            permissionKey: 'menu_branch',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/branches',
          },
          {
            id: 'programme',
            title: 'Programme',
            messageId: 'menu.programme',
            permissionKey: 'menu_programme',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/programmes',
          },
          {
            id: 'training_center',
            title: 'Training Center',
            messageId: 'menu.training_center',
            permissionKey: 'menu_training_center',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/training-centers',
          },
          {
            id: 'course',
            title: 'Course',
            messageId: 'menu.course',
            permissionKey: 'menu_course',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/courses',
          },
          {
            id: 'batch',
            title: 'Batch',
            messageId: 'menu.batch',
            permissionKey: 'menu_batch',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/batches',
          },
          {
            id: 'trainers',
            title: '',
            messageId: 'menu.trainers',
            permissionKey: 'menu_trainers',
            type: 'item',
            icon: 'timeline',
            url: '/dashboard/trainers',
          },
        ],
      },
      {
        id: 'location',
        title: 'Location',
        messageId: 'menu.location',
        type: 'collapse',
        icon: 'room',
        children: [
          {
            id: 'division',
            title: 'Division',
            messageId: 'menu.division',
            permissionKey: 'menu_division',
            type: 'item',
            icon: 'room',
            url: '/dashboard/divisions',
          },
          {
            id: 'district',
            title: 'District',
            messageId: 'menu.district',
            permissionKey: 'menu_district',
            type: 'item',
            icon: 'room',
            url: '/dashboard/districts',
          },
          {
            id: 'upazila',
            title: 'Upazila',
            messageId: 'menu.upazila',
            permissionKey: 'menu_upazila',
            type: 'item',
            icon: 'room',
            url: '/dashboard/upazilas',
          },
        ],
      },
    ],
  },
];
export default routesConfig;
