let a = {
  info: {
    _postman_id: 'e8dd90f1-ccf9-417f-99b5-86dedee55aae',
    name: 'NascibMembers',
    schema:
      'https://schema.getpostman.com/json/collection/v2.0.0/collection.json',
  },
  item: [
    {
      name: 'open-registration',
      id: 'beb67d66-e02e-4612-8887-b57ff42a784d',
      request: {
        method: 'POST',
        header: [{key: 'Domain', value: 'basis.org.bd', type: 'text'}],
        body: {
          mode: 'urlencoded',
          urlencoded: [
            {key: 'form_fill_up_by', value: '1', type: 'text'},

            {key: 'udc_name', value: 'udc_name', type: 'text'},
            {key: 'udc_loc_district', value: '1', type: 'text'},
            {key: 'udc_union', value: '1', type: 'text'},
            {key: 'udc_code', value: '1000', type: 'text'},
            {
              key: 'chamber_or_association_name',
              value: 'chamber_or_association_name',
              type: 'text',
            },
            {
              key: 'chamber_or_association_loc_district_id',
              value: '1',
              type: 'text',
            },
            {key: 'chamber_or_association_union_id', value: '1', type: 'text'},
            {
              key: 'chamber_or_association_code',
              value: 'code0101',
              type: 'text',
            },

            {key: 'entrepreneur_name', value: 'First Name', type: 'text'},
            {key: 'entrepreneur_name_en', value: 'Last Name', type: 'text'},
            {key: 'entrepreneur_gender', value: '1', type: 'text'},
            {
              key: 'entrepreneur_date_of_birth',
              value: '1991-01-01',
              type: 'text',
            },
            {
              key: 'entrepreneur_educational_qualification',
              value: 'BSc Engineer',
              type: 'text',
            },
            {key: 'entrepreneur_nid', value: '17000101010101', type: 'text'},
            {
              key: 'entrepreneur_nid_file_path',
              value: 'https://www.test.com',
              type: 'text',
            },
            {key: 'entrepreneur_mobile', value: '01767777006', type: 'text'},
            {
              key: 'entrepreneur_email',
              value: 'entrepreneur@gmail.com',
              type: 'text',
            },
            {
              key: 'entrepreneur_photo_path',
              value: 'entrepreneur_photo_path.png',
              type: 'text',
            },

            //organization information
            {key: 'title', value: 'Nascib Organization', type: 'text'},
            {key: 'title_en', value: 'Nascib Organization en', type: 'text'},
            {
              key: 'address',
              value: 'Nascib Organization address',
              type: 'text',
            },
            {
              key: 'address_en',
              value: 'Nascib Organization address en',
              type: 'text',
            },
            {key: 'loc_division_id', value: '1', type: 'text'},
            {key: 'loc_district_id', value: '1', type: 'text'},
            {key: 'loc_upazila_id', value: '1', type: 'text'},
            {key: 'domain', value: 'domain', type: 'text'},
            {key: 'identification_no', value: 'SBD20222M', type: 'text'},
            {key: 'is_proprietorship', value: '1', type: 'text'},
            {key: 'date_of_establishment', value: '2007-01-01', type: 'text'},
            {key: 'trade_licensing_authority', value: '1', type: 'text'},
            {key: 'trade_license_no', value: '19199195dd134434', type: 'text'},
            {
              key: 'trade_license_path',
              value: 'trade_license_path',
              type: 'text',
            },
            {key: 'trade_license_last_renew_year', value: '2019', type: 'text'},
            {key: 'have_tin', value: '1', type: 'text'},
            {key: 'investment_amount', value: '1000', type: 'text'},
            {key: 'current_total_asset', value: '1000', type: 'text'},
            {key: 'is_registered_under_authority', value: '1', type: 'text'},
            {
              key: 'registered_authority[1][authority_type]',
              value: '1',
              type: 'text',
            },
            {
              key: 'registered_authority[1][registration_number]',
              value: '366363633',
              type: 'text',
            },
            {
              key: 'registered_authority[2][authority_type]',
              value: '2',
              type: 'text',
            },
            {
              key: 'registered_authority[2][registration_number]',
              value: '36636363333',
              type: 'text',
            },
            {key: 'is_authorized_under_authority', value: '1', type: 'text'},
            {
              key: 'authorized_authority[1][authority_type]',
              value: '1',
              type: 'text',
            },
            {
              key: 'authorized_authority[1][registration_number]',
              value: '1443333333',
              type: 'text',
            },
            {
              key: 'authorized_authority[2][authority_type]',
              value: '1',
              type: 'text',
            },
            {
              key: 'authorized_authority[2][registration_number]',
              value: '1443333333',
              type: 'text',
            },
            {
              key: 'authorized_authority[other_authority][authority_name]',
              value: '1',
              type: 'text',
            },
            {
              key: 'authorized_authority[other_authority][register_number]',
              value: '1443333333',
              type: 'text',
            },
            {
              key: 'other_authority_name',
              value: 'ABC Other Authority',
              type: 'text',
            },
            {
              key: 'other_authority_registration_number',
              value: '1818818181',
              type: 'text',
            },
            {key: 'have_specialized_area', value: '1', type: 'text'},
            {key: 'specialized_area[]', value: '1', type: 'text'},
            {key: 'specialized_area[]', value: '2', type: 'text'},
            {
              key: 'is_under_of_association_or_chamber',
              value: '1',
              type: 'text',
            },
            {
              key: 'under_association_or_chamber_name',
              value: 'under_association_or_chamber_name',
              type: 'text',
            },
            {
              key: 'under_association_or_chamber_name_en',
              value: 'under_association_or_chamber_name_en',
              type: 'text',
            },
            {key: 'sector_id', value: '1', type: 'text'},
            {
              key: 'other_sector_name',
              value: 'other_sector_name',
              type: 'text',
            },
            {
              key: 'other_sector_name_en',
              value: 'other_sector_name_en',
              type: 'text',
            },
            {key: 'business_type', value: '1', type: 'text'},
            {
              key: 'main_product_name',
              value: 'main_product_name',
              type: 'text',
            },
            {
              key: 'main_product_name_en',
              value: 'main_product_name_en',
              type: 'text',
            },
            {
              key: 'main_material_description',
              value: 'main_material_description',
              type: 'text',
            },
            {
              key: 'main_material_description_en',
              value: 'main_material_description_en',
              type: 'text',
            },
            {key: 'is_import', value: '1', type: 'text'},
            {key: 'import_type[]', value: '1', type: 'text'},
            {key: 'import_type[]', value: '2', type: 'text'},
            {key: 'industry_irc_no', value: '3737737373737', type: 'text'},
            {key: 'is_export', value: '1', type: 'text'},
            {key: 'export_type[]', value: '1', type: 'text'},
            {key: 'export_type[]', value: '2', type: 'text'},
            {key: 'have_bank_account', value: '0', type: 'text'},
            {key: 'have_internet_connection', value: '1', type: 'text'},
            {key: 'have_online_business', value: '1', type: 'text'},
            {key: 'industry_association_id', value: '1', type: 'text'},
            {key: 'permission_sub_group_id', value: '1', type: 'text'},
            {
              key: 'info_provider_name',
              value: 'info_provider_name',
              type: 'text',
            },
            {key: 'info_provider_mobile', value: '0176777111', type: 'text'},
            {
              key: 'info_collector_name',
              value: 'info_collector_name',
              type: 'text',
            },
            {key: 'info_collector_mobile', value: '0176777111', type: 'text'},

            {key: 'have_factory', value: '1', type: 'text'},
            {key: 'factory_address', value: 'factory_address', type: 'text'},
            {
              key: 'factory_address_en',
              value: 'factory_address_en',
              type: 'text',
            },
            {key: 'factory_loc_division_id', value: '1', type: 'text'},
            {key: 'factory_loc_district_id', value: '1', type: 'text'},
            {key: 'factory_loc_upazila_id', value: '1', type: 'text'},
            {key: 'factory_web_site', value: 'factory_web_site', type: 'text'},
            {key: 'have_own_land', value: '1', type: 'text'},
            {key: 'have_office_or_showroom', value: '1', type: 'text'},
            {key: 'is_under_sme_cluster', value: '1', type: 'text'},
            {key: 'under_sme_cluster_id', value: '1', type: 'text'},
            {key: 'use_computer', value: '1', type: 'text'},
            {
              key: 'salaried_manpower[permanent_worker][male]',
              value: '10101',
              type: 'text',
            },
            {
              key: 'salaried_manpower[permanent_worker][female]',
              value: '201',
              type: 'text',
            },
            {
              key: 'salaried_manpower[temporary_worker][male]',
              value: '10000',
              type: 'text',
            },
            {
              key: 'salaried_manpower[temporary_worker][female]',
              value: '1000',
              type: 'text',
            },
            {
              key: 'salaried_manpower[seasonal_worker][male]',
              value: '100',
              type: 'text',
            },
            {
              key: 'salaried_manpower[seasonal_worker][female]',
              value: '200',
              type: 'text',
            },
            {key: 'bank_account_type[personal]', value: '1', type: 'text'},
            {key: 'bank_account_type[industry]', value: '1', type: 'text'},
            {key: 'have_daily_accounting_system', value: '1', type: 'text'},
          ],
        },
        url: '{{baseUrl}}/public/nascib-members/open-registration',
      },
      response: [],
    },
    {
      name: 'get-static-data',
      id: '4dda7845-6b25-48b7-8924-8b97af54c5a0',
      request: {
        method: 'GET',
        header: [{key: 'Domain', value: 'basis.org.bd', type: 'text'}],
        url: '{{baseUrl}}/public/nascib-members/get-static-data',
      },
      response: [],
    },
  ],
  event: [
    {
      listen: 'prerequest',
      script: {
        id: '4d540b06-3b64-4135-8948-75df996cfbd7',
        type: 'text/javascript',
        exec: [''],
      },
    },
    {
      listen: 'test',
      script: {
        id: '1ce163ff-dade-4eef-a8b1-971079b4dc14',
        type: 'text/javascript',
        exec: [''],
      },
    },
  ],
  variable: [
    {
      id: '24780880-f417-4037-9fa0-94a0f318719d',
      key: 'baseUrl',
      value: 'http://nise3.org/api/v1',
      type: 'string',
    },
  ],
};
