export default {
  id: 23,
  title: 'বিটাক',
  title_en: 'Bitac',
  domain: 'http://bitac.nise3.com',
  code: 'bitac',
  address: 'বাংলাদেশ শিল্প কারিগরি সহায়তা কেন্দ্র (বিটাক) ১১৬ (খ)',
  loc_division_id: 3,
  division_title: 'ঢাকা',
  division_title_en: 'Dhaka',
  loc_district_id: 18,
  district_title: 'ঢাকা',
  district_title_en: 'DHAKA',
  loc_upazila_id: 112,
  upazila_title: 'তেজগাঁও উন্নয়ন সার্কেল',
  upazila_title_en: 'TEJGAON UNNAYAN CIRCLE',
  primary_phone: '',
  phone_numbers: [],
  primary_mobile: '01521306222',
  mobile_numbers: [],
  email: 'ict@btac.gov.bd',
};
