export default {
  id: 26,
  title: 'যুব উন্নয়ন অধিদপ্তর',
  title_en: 'DYD',
  domain: 'https://dyd.nise.gov.bd',
  code: 'dyd',
  address: 'যুব উন্নয়ন অধিদপ্তর , যুব ভবন ১০৮, মতিঝিল বা/এ, ঢাকা-১০০০',
  loc_division_id: 3,
  division_title: 'ঢাকা',
  division_title_en: 'Dhaka',
  loc_district_id: 18,
  district_title: 'ঢাকা',
  district_title_en: 'DHAKA',
  loc_upazila_id: null,
  upazila_title: null,
  upazila_title_en: null,
  primary_phone: '',
  phone_numbers: [],
  primary_mobile: '01681111111',
  mobile_numbers: [],
  email: 'dyd@nise.gov.bd',
};
