const jobLists = [
  {
    id: 1,
    title: 'Title',
    industry_id: 1,
    job_id: 'IDSA-2fe8e68e-4456-43be-9d9d-481974a41890',
    position: 'Software Engr',
    industry: 'Softbd',
    job_type_id: 1,
    salary_range: '30k-50k',
    educational_qualification: 'test',
    certification: 'nextjs',
    loc_division_id: 1,
    loc_district_id: 1,
    loc_upazilla_id: 1,
    zone_id: 1,
    location: 'Dhaka',
    no_of_vacancy: 7,
    no_of_applicant: 10,
  },
  {
    id: 2,
    title: 'Title',
    industry_name: 'Industry',
    job_id: 'IDSA-2fe8e68e-4456-43be-9d9d-481974a41890',
    position: 'Software Engr',
    industry: 'Softbd',
    job_type: 'Private',
    salary_range: '30k-50k',
    educational_qualification: 'test',
    certification: 'nextjs',
    division: 'Dhaka',
    district: 'Dhaka',
    upazilla: 'Dhala',
    zone: 'Dhaka',
    location: 'Dhaka',
    no_of_vacancy: 7,
    no_of_applicant: 18,
  },
  {
    id: 3,
    title: 'Title',
    industry_name: 'Industry',
    job_id: 'IDSA-2fe8e68e-4456-43be-9d9d-481974a41890',
    position: 'Software Engr',
    industry: 'Softbd',
    job_type: 'Private',
    salary_range: '30k-50k',
    educational_qualification: 'test',
    certification: 'nextjs',
    division: 'Dhaka',
    district: 'Dhaka',
    upazilla: 'Dhala',
    zone: 'Dhaka',
    location: 'Dhaka',
    no_of_vacancy: 7,
    no_of_applicant: 20,
  },
];

export default jobLists;
