enum CourseDetailsTabs {
  TAB_OVERVIEW = 'TAB_OVERVIEW',
  TAB_LESSON = 'TAB_LESSON',
  TAB_EVALUATION_SYSTEM = 'TAB_EVALUATION_SYSTEM',
  TAB_REQUIREMENTS = 'TAB_REQUIREMENTS',
  TAB_TRAINING_METHODOLOGY = 'TAB_TRAINING_METHODOLOGY',
  TAB_OBJECTIVE = 'TAB_OBJECTIVE',
  TAB_ELIGIBILITY = 'TAB_ELIGIBILITY',
  TAB_TARGET_GROUP = 'TAB_TARGET_GROUP',
  TAB_TRAINER = 'TAB_TRAINER',
}

export default CourseDetailsTabs;
