export const hrDemand = [
  {
    id: 1,
    institute_name: '3A Fashion Ltd.',
    industry_name: 'Lead Soft',
    no_of_vacancy: '06',
    skills: 'Designing',
  },
  {
    id: 2,
    institute_name: '3A IT',
    industry_name: 'SoftBD',
    no_of_vacancy: '16',
    skills: 'Designing',
  },
  {
    id: 3,
    institute_name: '3A Fashion Ltd.',
    industry_name: 'SoftBD',
    no_of_vacancy: '22',
    skills: 'Designing',
  },
  {
    id: 4,
    institute_name: '3A Fashion Ltd.',
    industry_name: 'Lead Soft',
    no_of_vacancy: '02',
    skills: 'Designing',
  },
  {
    id: 5,
    institute_name: '3A Fashion Ltd.',
    industry_name: 'Lead Soft',
    no_of_vacancy: '05',
    skills: 'Designing',
  },
  {
    id: 6,
    institute_name: '3A Fashion Ltd.',
    industry_name: 'Lead Soft',
    no_of_vacancy: '15',
    skills: 'Designing',
  },
  {
    id: 7,
    institute_name: '3A Fashion Ltd.',
    industry_name: 'Lead Soft',
    no_of_vacancy: '06',
    skills: 'Designing',
  },
];
