import {IAssociationMember} from '../../../shared/Interface/industryAssociation.interface';

export const members: Array<IAssociationMember> = [
  {
    id: 1,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 2,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 3,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 4,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 5,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 6,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 7,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 8,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
  {
    id: 9,
    organization_type_id: 2,
    title: 'Lead Soft',
    title_en: 'Klein-Luettgen',
    loc_division_id: 2,
    loc_district_id: 10,
    loc_upazila_id: 2,
    location_latitude: '91.815526',
    location_longitude: '91.815526',
    google_map_src: 'test map src',
    address: 'তেজগাও, ঢাকা।',
    address_en: '6460 King Extensions Romagueraview, MN 03114-5832',
    country: 'BD',
    phone_code: '880',
    mobile: '০১৬৮০০৪৯৭৫৫',
    email: 'mario.cronin@murphy.com',
    fax_no: '০১৬৮০০৪৯৭৫৫',
    name_of_the_office_head: 'Margarete Abshire',
    name_of_the_office_head_en: 'Margarete Abshire',
    name_of_the_office_head_designation: 'বেবস্থাপনা পরিচালক',
    name_of_the_office_head_designation_en: 'CEO',
    contact_person_name: 'মোঃ হাসাণউল্লাহ্',
    contact_person_name_en: 'Ayana Weissnat',
    contact_person_mobile: '০১৬৮০০৪৯৭৫৫',
    contact_person_email: 'conroy@example.com',
    contact_person_designation: 'বেবস্থাপনা পরিচালক',
    contact_person_designation_en: 'Social Sciences Teacher',
    description:
      'এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন। এই আর্টিক্যালটি তাদেরই জন্য যারা শব্দের জাদুতে পাঠককে সম্মোহিত করে আনন্দ পান। লেখুনির মাধ্যমে মনের ভাব প্রকাশ করেন।',
    description_en: 'Aut tempore est quas atque vero.',
    logo: '/images/lead_soft.svg',
    domain: 'https://www.considine.com/',
    row_status: '1',
    created_at: '09-12-2021',
  },
];
//   members:
//   isLoading: false,
//   total_page: 2,
