apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Chart.Name }}
  labels:
    app:  {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}
  replicas: {{ .Values.variables.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.variables.imageRepository }}:{{ .Values.variables.imageAppVersion  | default .Chart.AppVersion }}"
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.variables.imagePullPolicy }}
          ports:
            - containerPort: 3006
      imagePullSecrets:
        - name: regcred
---
{{ if (.Values.autoScaling.enabled) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: {{ .Values.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.autoScaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoScaling.stabilizationWindowSecondsForScaleDown }}
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
{{end}}
