export enum ApplyStatuses {
  APPLIED = 1,
  REJECTED = 2,
  SHORTLISTED = 3,
  INTERVIEW_SCHEDULED = 4,
  INTERVIEW_INVITED = 5,
  INTERVIEWED = 6,
  HIRING_LISTED = 7,
  HIRE_INVITED = 8,
  HIRED = 9,
}
