export enum IndustryDashboardTabs {
  INDUSTRY = 'INDUSTRY',
  UNEMPLOYED_PEOPLE = 'UNEMPLOYED_PEOPLE',
  JOB_VACANCY = 'JOB_VACANCY',
  EMPLOYED_PEOPLE = 'EMPLOYED_PEOPLE',
  SKILLED_PEOPLE = 'SKILLED_PEOPLE',
}
