// https://transform.tools/css-to-js

const ChartCSS = {
  '.orgchart-container': {
    boxSizing: 'border-box',
    position: 'relative',
    margin: '10px',
    height: '700px',
    backgroundColor: '#fff',
    border: '2px dashed #aaa',
    borderRadius: '5px',
    overflow: 'auto',
    textAlign: 'center',
  },
  '.orgchart': {
    boxSizing: 'border-box',
    display: 'inline-block',
    backgroundImage:
      'linear-gradient(90deg, rgba(200, 0, 0, 0.15) 10%, rgba(0, 0, 0, 0) 10%), linear-gradient(rgba(200, 0, 0, 0.15) 10%, rgba(0, 0, 0, 0) 10%)',
    backgroundSize: '10px 10px',
    border: '1px dashed rgba(0,0,0,0)',
    padding: '20px 20px 0 20px',
  },
  '.orgchart-container .hidden': {display: 'none !important'},
  '.orgchart-container > .oc-mask': {
    position: 'absolute',
    top: '0',
    right: '0',
    bottom: '0',
    left: '0',
    zIndex: 999,
    textAlign: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  '.orgchart-container > .oc-mask .spinner': {
    position: 'absolute',
    top: 'calc(50% - 50px)',
    left: 'calc(50% - 50px)',
  },
  '.orgchart-container > .oc-mask .spinner::before': {
    width: '100px',
    height: '100px',
    borderWidth: '10px',
    borderRadius: '50px',
    borderTopColor: 'rgba(68, 157, 68, 0.8)',
    borderBottomColor: 'rgba(68, 157, 68, 0.8)',
    borderLeftColor: 'rgba(68, 157, 68, 0.8)',
  },

  /* ********************************* */

  '.orgchart ul': {
    paddingLeft: '0',
    textAlign: 'center',
    display: 'flex',
    margin: '0',
    transition: 'transform 0.3s, opacity 0.3s',
  },
  '.orgchart ul li': {display: 'inline-block', position: 'relative'},
  '.orgchart > ul > li > ul li::before': {
    content: '""',
    position: 'absolute',
    top: '-11px',
    left: '0',
    width: '100%',
    borderTop: '2px solid rgba(217, 83, 79, 0.8)',
    boxSizing: 'border-box',
  },
  '.orgchart > ul > li > ul li.isSiblingsCollapsed::before': {
    content: 'none',
  },
  '.orgchart > ul > li > ul li:first-child::before': {
    left: 'calc(50% - 1px)',
    width: 'calc(50% + 1px)',
  },
  '.orgchart > ul > li > ul li:last-child::before': {
    width: 'calc(50% + 1px)',
  },
  '.orgchart > ul > li > ul li:only-child::before': {width: '2px'},
  '.orgchart ul li .oc-node': {
    boxSizing: 'border-box',
    display: 'inline-block',
    position: 'relative',
    padding: '3px',
    border: '2px dashed transparent',
    marginBottom: '20px',
  },
  '.orgchart ul li .oc-node.allowedDrop': {
    borderColor: 'rgba(68, 157, 68, 0.9)',
  },
  '.orgchart ul li .oc-node.currentDropTarget': {
    backgroundColor: 'rgba(68, 157, 68, 0.9)',
  },
  '.orgchart ul li .oc-node.selected': {
    backgroundColor: 'rgba(238, 217, 54, 0.5)',
  },
  '.orgchart ul li .oc-node:hover': {
    backgroundColor: 'rgba(238, 217, 54, 0.5)',
  },
  '.orgchart > ul > li > ul li > .oc-node::before': {
    content: '""',
    position: 'absolute',
    top: '-11px',
    left: 'calc(50% - 1px)',
    width: '2px',
    height: '9px',
    backgroundColor: 'rgba(217, 83, 79, 0.8)',
  },
  '.orgchart > ul > li > ul li.isSiblingsCollapsed > .oc-node::before': {
    top: '-13px',
    height: '11px',
  },
  '.orgchart > ul > li > ul li.isAncestorsCollapsed > .oc-node::before': {
    content: 'none',
  },
  '.orgchart ul li .oc-node:not(:only-child)::after': {
    content: '""',
    position: 'absolute',
    bottom: '-11px',
    left: 'calc(50% - 1px)',
    width: '2px',
    height: '9px',
    backgroundColor: 'rgba(217, 83, 79, 0.8)',
  },
  '.orgchart ul li .oc-node.isChildrenCollapsed:not(:only-child)::after': {
    content: 'none',
  },
  '.orgchart ul li .oc-node .oc-heading': {
    boxSizing: 'border-box',
    padding: '2px',
    margin: '0',
    width: '130px',
    height: '20px',
    textAlign: 'center',
    fontSize: '0.75rem',
    fontWeight: 'bold',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    backgroundColor: 'rgba(217, 83, 79, 0.8)',
    color: '#fff',
    borderRadius: '4px 4px 0 0',
  },
  '.orgchart ul li .oc-node .oc-heading .oc-symbol': {
    cssFloat: 'left',
    marginTop: '12px',
    marginLeft: '2px',
  },
  '.orgchart ul li .oc-node .oc-heading .oc-symbol::before': {
    backgroundColor: '#fff',
    borderColor: 'rgba(217, 83, 79, 0.8)',
  },
  '.orgchart ul li .oc-node .oc-heading .oc-symbol::after': {
    backgroundColor: '#fff',
  },
  '.orgchart ul li .oc-node .oc-content': {
    boxSizing: 'border-box',
    padding: '2px',
    width: '130px',
    height: '20px',
    fontSize: '0.625rem',
    border: '1px solid rgba(217, 83, 79, 0.8)',
    borderRadius: '0 0 4px 4px',
    textAlign: 'center',
    backgroundColor: '#fff',
    color: '#333',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.orgchart .oc-node .oc-edge': {
    position: 'absolute',
    cursor: 'default',
    transition: '.2s',
  },
  '.orgchart .oc-node .oc-edge::before': {
    borderColor: 'rgba(68, 157, 68, 0.5)',
  },
  '.orgchart.noncollapsable .oc-node .oc-edge': {display: 'none'},
  '.orgchart .oc-node .oc-edge:hover': {cursor: 'pointer'},
  '.orgchart .oc-edge:hover::before': {borderColor: '#449d44'},
  '.orgchart .oc-node .verticalEdge': {
    width: [
      'calc(100% - 6px)',
      '-webkit-calc(100% - 6px)',
      '-moz-calc(100% - 6px)',
    ],
    height: '10px',
    left: '3px',
  },
  '.orgchart .oc-node .verticalEdge::before': {
    position: 'absolute',
    left: 'calc(50% - 0.3125rem)',
  },
  '.orgchart .oc-node .topEdge': {top: '-2px'},
  '.orgchart .oc-node .topEdge.oci-chevron-up::before': {top: '2px'},
  '.orgchart .oc-node .topEdge.oci-chevron-down::before': {bottom: '3px'},
  '.orgchart .oc-node .bottomEdge': {bottom: '-2px'},
  '.orgchart .oc-node .bottomEdge.oci-chevron-up::before': {bottom: '-3px'},
  '.orgchart .oc-node .bottomEdge.oci-chevron-down::before': {bottom: '1px'},
  '.orgchart .oc-node .horizontalEdge': {
    width: '10px',
    height: [
      'calc(100% - 6px)',
      '-webkit-calc(100% - 6px)',
      '-moz-calc(100% - 6px)',
    ],
    top: '3px',
  },
  '.orgchart .oc-node .rightEdge': {right: '-2px'},
  '.orgchart .oc-node .leftEdge': {left: '-2px'},
  '.orgchart .oc-node .horizontalEdge::before': {
    position: 'absolute',
    top: 'calc(50% - 0.3125rem)',
  },
  '.orgchart .oc-node .rightEdge.oci-chevron-left::before': {right: '-3px'},
  '.orgchart .oc-node .rightEdge.oci-chevron-right::before': {right: '1px'},
  '.orgchart .oc-node .leftEdge.oci-chevron-right::before': {left: '-3px'},
  '.orgchart .oc-node .leftEdge.oci-chevron-left::before': {left: '1px'},
  '.orgchart .slide-up': {opacity: 0, transform: 'translateY(-40px)'},
  '.orgchart .slide-down': {opacity: 0, transform: 'translateY(40px)'},
  '.orgchart .slide-left': {opacity: 0, transform: 'translateX(-130px)'},
  '.orgchart .slide-right': {opacity: 0, transform: 'translateX(130px)'},
  '.oci': {
    display: 'inline-block',
    position: 'relative',
    fontStyle: 'normal',
    fontFamily: 'Arial',
  },
  '.oci-chevron-up::before': {
    content: '""',
    display: 'inline-block',
    boxSizing: 'border-box',
    verticalAlign: 'text-bottom',
    width: '0.625rem',
    height: '0.625rem',
    borderWidth: '0 0.2rem 0.2rem 0',
    borderStyle: 'solid',
    borderColor: '#000',
    background: 'transparent',
    transform: 'rotate(-135deg)',
  },
  '.oci-chevron-right::before': {
    content: '""',
    display: 'inline-block',
    boxSizing: 'border-box',
    width: '0.625rem',
    height: '0.625rem',
    borderWidth: '0 0.2rem 0.2rem 0',
    borderStyle: 'solid',
    borderColor: '#000',
    background: 'transparent',
    transform: 'rotate(-45deg)',
  },
  '.oci-chevron-down::before': {
    content: '""',
    display: 'inline-block',
    boxSizing: 'border-box',
    width: '0.625rem',
    height: '0.625rem',
    borderWidth: '0 0.2rem 0.2rem 0',
    borderStyle: 'solid',
    borderColor: '#000',
    background: 'transparent',
    transform: 'rotate(45deg)',
  },
  '.oci-chevron-left::before': {
    content: '""',
    display: 'inline-block',
    boxSizing: 'border-box',
    width: '0.625rem',
    height: '0.625rem',
    borderWidth: '0 0.2rem 0.2rem 0',
    borderStyle: 'solid',
    borderColor: '#000',
    background: 'transparent',
    transform: 'rotate(135deg)',
  },
  '.oci-leader::before': {
    position: 'absolute',
    content: '""',
    display: 'inline-block',
    width: '0.4rem',
    height: '0.4rem',
    borderRadius: '0.2rem',
    background: '#000',
    top: '-0.75rem',
    left: '0.125rem',
  },
  '.oci-leader::after': {
    position: 'absolute',
    content: '""',
    display: 'inline-block',
    width: '0.875rem',
    height: '0.375rem',
    borderRadius: '0.25rem 0.25rem 0 0',
    background: '#000',
    top: '-0.3rem',
    left: '-0.125rem',
  },
  '.oci-plus-square::before': {
    content: '"+"',
    display: 'inline-block',
    verticalAlign: 'text-bottom',
    textAlign: 'center',
    width: '1rem',
    height: '1rem',
    backgroundColor: '#000',
    color: '#fff',
  },
  '.oci-plus-circle::before': {
    content: '"+"',
    display: 'inline-block',
    verticalAlign: 'text-bottom',
    textAlign: 'center',
    width: '1rem',
    height: '1rem',
    borderRadius: '0.5rem',
    backgroundColor: '#000',
    color: '#fff',
  },
  '.oci-minus-square::before': {
    content: '"−"',
    display: 'inline-block',
    verticalAlign: 'text-bottom',
    textAlign: 'center',
    width: '1rem',
    height: '1rem',
    backgroundColor: '#000',
    color: '#fff',
  },
  '.oci-minus-circle::before': {
    content: '"−"',
    display: 'inline-block',
    verticalAlign: 'text-bottom',
    textAlign: 'center',
    width: '1rem',
    height: '1rem',
    borderRadius: '0.5rem',
    backgroundColor: '#000',
    color: '#fff',
  },
  '.oci-arrow-circle-up::before': {
    content: '"▲"',
    display: 'inline-block',
    textAlign: 'center',
    verticalAlign: 'text-bottom',
    width: '1rem',
    height: '1rem',
    borderRadius: '0.5rem',
    backgroundColor: '#000',
    color: '#fff',
    fontSize: '0.875rem',
  },
  '.oci-arrow-circle-down::before': {
    content: '"▼"',
    textAlign: 'center',
    display: 'inline-block',
    verticalAlign: 'text-bottom',
    width: '1rem',
    height: '1rem',
    borderRadius: '0.5rem',
    backgroundColor: '#000',
    color: '#fff',
    fontSize: '0.875rem',
  },
  '.oci-info-circle::before': {
    content: '"i"',
    display: 'inline-block',
    verticalAlign: 'text-bottom',
    width: '1rem',
    height: '1rem',
    borderRadius: '0.5rem',
    backgroundColor: '#000',
    color: '#fff',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  '.oci-spinner::before': {
    content: '""',
    verticalAlign: 'text-bottom',
    display: 'inline-block',
    boxSizing: 'border-box',
    width: '1rem',
    height: '1rem',
    border: '0.1rem solid #000',
    borderRightColor: 'transparent',
    borderRadius: '0.625rem',
    animation: 'oci-infinite-spinning .75s linear infinite',
  },
  '@keyframes oci-infinite-spinning': {
    from: {transform: 'rotate(0deg)'},
    to: {transform: 'rotate(360deg)'},
  },
};

export default ChartCSS;
